baseurl = "https://www.konfound-it.org/"
languageCode = "en-us"
title = "KonFound-it!"
theme = "blackburn"
author = "KonFound-it Group"
copyright = "&copy; 2020. All rights reserved."
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#canonifyurls = true
paginate = 10
math = true

[permalinks]
post = "/:year/:month/:day/:slug"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Conversations about quantifying the robustness of inferences."
  brand = "KonFound-it!"
  googleAnalytics = "UA-166232587-1"
  disqus = "konfoundcovid"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "2006/01/02"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Workshops"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 3
    identifier = "workshops"
    url = "/workshops/"
  [[menu.main]]
    name = "Publications"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 4
    identifier = "publications"
    url = "/publications/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 6
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "kenfrank20"
  github = "linqinyu/KonFound-blog"
